---
- name: install apache
  apt: name=apache2 state=present
- name: copy across new vhost
  template: 
    src=virtual-hosts.conf.j2 
    dest=/etc/apache2/sites-available/vagrant.conf
  notify:
    - reload apache
- name: remove default vhost
  file: 
    path=/etc/apache2/sites-enabled/000-default.conf
    state=absent
  notify:
    - reload apache
- name: Enable new vagrant host
  file: 
    src=/etc/apache2/sites-available/vagrant.conf
    dest=/etc/apache2/sites-enabled/vagrant.conf
    state=link
  notify:
    - reload apache